name: ✨ Sugestão (site)
description: Sugira melhorias para o BotAssist Site (este repositório).
title: "[Sugestão]: "
body:
  - type: markdown
    attributes:
      value: |
        Ideias são bem-vindas — o objetivo é colaborar com software livre, gratuito e de qualidade.

        Se a sugestão for do **aplicativo**, use: https://github.com/N1ghthill/botassist-whatsapp/issues
  - type: textarea
    id: problem
    attributes:
      label: Qual problema você quer resolver?
      placeholder: "Ex.: Hoje é difícil encontrar..."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Sua sugestão
      placeholder: "Ex.: Poderia ter um botão/uma seção..."
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Contexto adicional (opcional)
      placeholder: "Links, prints, referências..."
    validations:
      required: false
